# Generated by Django 4.1.4 on 2023-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('today_date', models.DateField(auto_now=True)),
                ('User_age', models.DecimalField(decimal_places=0, max_digits=4)),
                ('User_email', models.EmailField(max_length=245)),
            ],
        ),
    ]
